;Josh's direct input key and group equates
reset .equ 0ffh

Group1 .equ 0feh
Group2 .equ 0fdh
Group3 .equ 0fbh
Group4 .equ 0f7h
Group5 .equ 0efh
Group6 .equ 0dfh
Group7 .equ 0bfh

;Group 1 
KDown		.equ 254 
KLeft		.equ 253 
KRight		.equ 251 
KUp		.equ 247 

;Group 2 
KEnter		.equ 254 
KPlus		.equ 253 
KMinus		.equ 251 
KMul		.equ 247 
KDiv		.equ 239 
KPower		.equ 223 
KClear		.equ 191 

;Group 3 
kMinus2		.equ 254 
kThree		.equ 253 
kSix		.equ 251 
kNine		.equ 247 
kRbracket	.equ 239 
kTan		.equ 223 
kVars		.equ 191 

;Group 4 
KPoint		.equ 254 
KTwo		.equ 253 
KFive		.equ 251
KEight		.equ 247
KLbracket	.equ 239
KCos		.equ 223
KPrgm		.equ 191
KStat		.equ 127 

;Group 5 
KZero		.equ 254
KOne		.equ 253
KFour		.equ 251
KSeven		.equ 247
KComma		.equ 239
KSin		.equ 223
KMatrx		.equ 191
KX		.equ 127 

;Group 6 
KSto		.equ 253
KLn		.equ 251
KLog		.equ 247
kX2		.equ 239
kX-1		.equ 223
kMath		.equ 191
kAlpha		.equ 127 

;Group 7 
KGraph		.equ 254
KTrace		.equ 253
KZoom		.equ 251
KWindow		.equ 247
KY		.equ 239
k2nd		.equ 223
kMode		.equ 191
kDel		.equ 127